# services/nlp.py
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('all-MiniLM-L6-v2')

knowledge_base = [
    "IF the entrepreneur is starting a business for the first time, THEN recommend a checklist of legal procedures and suggest consultation with a business registration expert.",
    "IF the business involves regulated products (e.g., agriculture, food, cosmetics, or imported goods), THEN identify the specific licenses or approvals required and guide them to the relevant authorities.",
    "IF the entrepreneur expresses confusion about business registration, THEN provide step-by-step instructions and local agency contacts for registration assistance.",
    "IF the entrepreneur plans to import goods during a crisis or shortage (e.g., PPE during COVID-19), THEN verify if the product requires special permits and direct them to emergency importation guidelines.",
    "IF the entrepreneur uses B2C platforms (e.g., Taobao) for sourcing products, THEN alert them to the differences between personal and commercial import rules.",
    "IF the entrepreneur is importing in bulk, THEN recommend customs declaration processes, SIRIM/DVS/MITI requirements (if in Malaysia), and suggest hiring a licensed customs agent.",
    "IF a user is asking how to start a business with limited capital, a small budget, or as a student with no money, THEN first, choose a low-cost business model like providing a service, selling digital products, or dropshipping to keep initial expenses low. Your main strategy should be bootstrapping—using your personal savings carefully and avoiding non-essential costs. At the same time, you must actively apply for government grants designed for students from agencies like Cradle and MaGIC, as this is funding you don't have to pay back.",
    "IF the entrepreneur has not estimated startup and compliance costs, THEN prompt a financial assessment including registration fees, licensing, inventory, and operational costs.",
    "IF the entrepreneur seeks funding, THEN recommend funding options such as government grants, microloans, or angel investors.",
    "IF a user is unsure if their business idea is viable, will solve a real problem, or if customers will actually pay for it, THEN to validate your idea, start by conducting at least 10 'customer discovery' interviews with your target audience to understand their problems before you mention your solution. Based on their feedback, create a Minimum Viable Product (MVP)—the simplest version of your product that solves their core problem. Finally, test this MVP with a small group of users to see if they will actually use it and would be willing to pay.",
    "IF the entrepreneur is unsure about their competitiveness, THEN suggest performing a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) and competitive benchmarking.",
    "IF the entrepreneur has not studied competitors, THEN prompt them to identify at least 3 direct competitors and analyze their offerings, pricing, and value propositions.",
    "IF the entrepreneur is looking for funding opportunities, THEN suggest exploring innovation grants, government schemes, and startup competitions.",
    "IF the entrepreneur considers entering competitions, THEN advise them that competitions are also opportunities to gain visibility, receive feedback, and pitch to investors.",
    "IF the entrepreneur lacks pitching skills, THEN recommend training or practice sessions to build confidence and structure (problem-solution-benefits-traction model).",
    "IF the entrepreneur lacks funding but has technical knowledge, THEN suggest reaching out to potential partners in industry who might value their expertise and offer support.",
    "IF the entrepreneur is developing a high-cost or technical product, THEN recommend forming partnerships with entities that can provide licensing support, technical tools, or government access.",
    "IF the entrepreneur has no current industry contacts, THEN suggest attending industry expos, joining professional associations, or leveraging university networks to find partners.",
    "IF the entrepreneur is a startup with no historical data, THEN recommend using the “Three-Scope Projection” model (TAM, SAM, SOM) to estimate market size.",
    "IF the entrepreneur is unaware of market estimation techniques, THEN explain that large companies use data-driven models, but startups should rely on assumptions backed by research.",
    "IF the entrepreneur has identified their TAM, SAM, and SOM, THEN prompt them to justify each with logic, sources, or comparisons to similar startups or industries.",
    "IF the user is uncertain about starting a business, THEN prompt them to reflect on their personal goals, willingness to take risks, and ability to handle pressure.",
    "IF the user shows signs of underestimating entrepreneurial challenges, THEN alert them to common issues such as financial instability, lifestyle sacrifices, and mental stress.",
    "IF the user acknowledges the emotional and lifestyle sacrifices involved, THEN assess their long-term commitment and suggest creating a personal readiness checklist.",
    "IF the entrepreneur has no plan for sustaining the business in year one, THEN recommend calculating a 12-month cash flow projection, including fixed assets and operational costs.",
    "IF the entrepreneur cannot fund early growth, THEN suggest securing a financial buffer or identifying potential funding sources before launching.",
    "IF the entrepreneur has not considered delayed returns, THEN highlight that most startups don’t generate profits immediately and need financial patience.",
    "IF the entrepreneur plans to run the business solo, THEN warn about the risks of isolation and recommend seeking at least one reliable co-founder or advisor.",
    "IF the entrepreneur lacks industry contacts or strategic allies, THEN encourage them to build partnerships that can offer funding, domain expertise, and networking.",
    "IF the entrepreneur is unsure about partnership benefits, THEN explain that strong partners can improve sustainability by sharing workload, reducing costs, and opening doors.",
    "IF the business idea offers something new or better than existing solutions and addresses a real customer need, THEN it is considered to have a strong value proposition.",
    "IF the business idea does not offer something unique or does not solve a real problem, THEN it is considered not viable due to a weak value proposition.",
    "IF the business idea does not clearly define how it will generate income, THEN it is not viable.",
    "IF the business idea includes multiple well-defined revenue streams (e.g., online sales, in-store sales, subscription fees), THEN it is considered to have a strong revenue model.",
    "IF the product is still an idea OR at a very early concept stage, THEN its commercialization potential is low.",
    "IF the product is tested AND validated AND or close to launch, THEN it has a high commercialization potential.",
    "IF the idea has a strong value proposition AND multiple clear revenue streams AND high speed to market, THEN it is considered ready for investment.",
    "IF the business is small, simple, and managed by one person, THEN the sole proprietorship is the most suitable structure.",
    "IF the entrepreneur is confident in handling all operations alone and is comfortable with personal liability, THEN the sole proprietorship is appropriate.",
    "IF the entrepreneur wants to avoid risk to personal assets, THEN the sole proprietorship is not recommended.",
    "IF there are two or more founders, THEN a partnership is suitable.",
    "IF the entrepreneurs want to share responsibilities, pool resources, or avoid facing challenges alone, THEN a partnership is recommended.",
    "IF the business is started by young or first-time entrepreneurs, THEN a partnership is especially encouraged due to its flexibility and support structure.",
    "IF the entrepreneurs want limited liability but fewer legal formalities than a company, THEN an LLP is suitable.",
    "IF the business falls between a partnership and a Sendirian Berhad in terms of structure and needs, THEN an LLP is recommended.",
    "IF the business needs personal asset protection, THEN a Sendirian Berhad is suitable.",
    "IF the entrepreneur is prepared to comply with more legal and regulatory formalities, THEN a Sendirian Berhad is appropriate.",
    "IF the entrepreneur wants to limit liability strictly to company assets, THEN a Sendirian Berhad is the preferred choice.",
    "IF the entrepreneur is new and wants operational flexibility with shared responsibility, THEN starting with a partnership is recommended.",
    "IF the entrepreneur has personal savings or access to small informal loans from family/friends, THEN bootstrapping is a feasible option.",
    "IF the entrepreneur has strong motivation and personal discipline in managing money, THEN bootstrapping is recommended.",
    "IF the business is short-term or small-scale, THEN bootstrapping is a good initial funding method.",
    "IF the entrepreneur is not yet eligible or ready for formal funding sources, THEN bootstrapping should be used as a first step.",
    "IF the startup involves a socially impactful, innovative, or unique idea, THEN applying for government grants is recommended.",
    "IF the entrepreneur is willing to join competitions or pitch publicly, THEN government grants are a good option.",
    "IF the startup needs non-repayable funding or early support for idea development, THEN grants are ideal.",
    "IF the entrepreneur has no collateral or poor credit history, THEN applying through a government-guaranteed development bank is recommended.",
    "IF the startup requires moderate capital but the founder wants to avoid risking personal assets, THEN development bank loans are suitable.",
    "IF the entrepreneur prefers lower-risk loans with low interest rates or no collateral requirements, THEN government-backed bank loans are the best fit.",
    "IF the startup is looking for safer borrowing alternatives than commercial banks, THEN development bank funding is recommended.",
    "IF the business is growing and needs additional capital without risking personal assets, THEN consider microloans from banks or government agencies that don’t require collateral.",
    "IF the startup cannot afford advertising, THEN focus on organic SEO to increase visibility without spending on ads.",
    "IF the startup has limited budget, THEN avoid paid ads like Google Ads or Meta Ads.",
    "IF the target audience is active on social media, THEN use free platforms such as Instagram, TikTok, or Facebook.",
    "IF resources are limited, THEN limit marketing efforts to 2–3 platforms to maintain content consistency and credibility.",
    "IF using social media platforms, THEN utilize relevant hashtags to increase reach and engagement.",
    "IF the goal is to increase revenue per customer, THEN apply upselling by recommending higher-tier products.",
    "IF the goal is to increase basket size, THEN use cross-selling by suggesting complementary products.",
    "IF the goal is to encourage customer retention, THEN use next-sell techniques such as exclusive offers or future discounts.",
    "IF the customer segment is local, THEN tailor marketing efforts toward local needs and platforms.",
    "IF the target customers are young, THEN prioritize youth-friendly platforms like TikTok or Instagram.",
    "IF targeting older consumers, THEN focus on Facebook or platforms they frequently use.",
    "IF the business is oriented toward export markets, THEN align branding and marketing to international expectations and needs.",
    "IF target_customer is 'business', THEN business_model is 'B2B' AND explanation is 'Expect longer sales cycles, contracts, and larger order volumes.'",
    "IF target_customer is 'individual', THEN business_model is 'B2C' AND explanation is 'Focus on marketing, customer experience, and handling many small purchases.'",
    "IF delivery_method is 'recurring', THEN business_model is 'Subscription' AND explanation is 'You must deliver consistent value and focus on customer retention.'",
    "IF platform_type is 'connects buyers and sellers', THEN business_model is 'Marketplace' AND explanation is 'You\'ll need to manage a reliable platform and build trust among users.'",
    "IF most_profitable_segment is known, THEN advice is 'Start with the most profitable and manageable segment first.'",
    "IF business_model is not scalable, THEN advice is 'Reconsider the model. Look for options that scale better with fewer added costs.'",
    "IF unsure_about_model, THEN advice is 'Start with one model (e.g., B2C), test it with real users, and expand based on feedback and profitability.'",
    "IF political_or_economic_stability is False, THEN advice is 'Avoid launching now. Unstable conditions increase startup risk.'",
    "IF government_support is True, THEN advice is 'It may be a good time to launch. Take advantage of available grants or programs.'",
    "IF consumer_demand is increasing, THEN advice is 'There is rising demand. Consider launching to meet market needs.'",
    "IF technology_readiness is low, THEN advice is 'Delay launch until the technology is more mature or accessible.'",
    "IF current_period is a major crisis AND solution does NOT address crisis, THEN advice is 'Avoid launching during crisis unless your startup solves a direct crisis need.'",
    "IF current_period is stable AND purchasing_power is high AND demand_exists is True, THEN advice is 'This is an ideal time to launch. Conditions support startup growth.'",
    "IF cash_flow_tracking is False, THEN advice is 'Start tracking your cash flow closely. Make sure you always have enough liquidity for monthly operations.'",
    "IF funding_method is 'bootstrapping', THEN advice is 'Use bootstrapping wisely. Keep costs low and avoid unnecessary spending.'",
    "IF eligible_for_grants is True, THEN advice is 'Apply for government grants or student entrepreneur programs to get early funding.'",
    "IF participating_in_competitions is True, THEN advice is 'Join startup competitions. They’re a good source of seed funding and exposure.'",
    "IF have_access_to_investors is True, THEN advice is 'Reach out to angel investors or early-stage partners if needed, but stay lean.'",
    "IF using_tool is 'none', THEN advice is 'Use simple tools like Excel or Google Sheets to plan your budget and forecast revenue.'",
    "IF using_tool is 'accounting_software', THEN advice is 'Good! Tools like Wave, QuickBooks, or Xero can help you track finances more efficiently.'",
    "IF early_spending_on_marketing_or_hiring is True, THEN warning = 'Be careful. In the early stage, prioritize product development and validating your idea over heavy spending.'",
    "IF product_market_fit is not validated, THEN advice = 'Seek expert help to validate your idea. Make sure it solves a real, proven problem using evidence like statistics, reports, or customer interviews.'",
    "IF funding_strategy is unclear, THEN advice = 'Get advice on funding options. Depending on your business type, bootstrapping, grants, competitions, or micro-loans may be suitable.'",
    "IF cash_runway < 6_months, THEN advice = 'Talk to a financial advisor or mentor to extend your runway and plan sustainable cash flow.'",
    "IF founding_team is incomplete OR lacks complementary skills, THEN advice = 'Seek advice on team building. Choose co-founders who balance your weaknesses and share your vision.'",
    "IF legal_structure is not decided, THEN advice = 'Consult a legal advisor to pick the right structure (e.g., partnership, LLP, Sdn Bhd) to protect your interests and comply with local laws.'",
    "IF the cost of producing the product is high, THEN do not set the selling price too low, or the business will not be sustainable.",
    "IF your cost is low, THEN set a price with a higher markup to gain more profit margin.",
    "IF your product offers strong value-added features or unique advantages, THEN you can set a higher price confidently.",
    "IF your product is similar to competitors' offerings, THEN avoid setting the price too far above or below the existing market rate.",
    "IF your product targets underserved or low-income communities, THEN explore possibilities of government subsidies to offer lower prices and reach more people.",
    "IF you are able to get a government subsidy, THEN lower the product price to increase accessibility and expand your customer base.",
    "IF a potential team member cannot contribute meaningfully to your business model, THEN do not include them, even if you trust them personally.",
    "IF a team member has skills or resources (e.g., software, databases, coding) that fill a gap in your business, THEN include them as they provide key resources or activities.",
    "IF you are forming a startup team, THEN ensure it includes not only technical experts but also people with management and marketing skills.",
    "IF you are working with a team on a business project, THEN always register the business to legally define roles and profit-sharing, and prevent future conflicts.",
    "IF the economic situation is favorable (i.e., stable or growing), THEN it is a good time to enter the market.",
    "IF your product has strong competitive advantages or clear added value, THEN proceed confidently into the market, even at a higher price point.",
    "IF your product can address social problems or benefit a marginalized group, THEN look for opportunities to align your business with government or NGO support (e.g., grants, subsidies).",
    "IF your brand is already strong or credible, THEN you may enter the market at a premium price.",
    "IF your business solves both a market need and a social issue (e.g., empowering single mothers), THEN you achieve both sustainability and impact, making the business more valuable and fundable.",
    "IF you are eager to expand your business quickly after some initial success, THEN first conduct a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) to ensure your growth is strategic and sustainable, not just based on excitement.",
    "IF a user has created a unique invention, a software application, a creative work, or a proprietary formula, THEN you must protect your intellectual property immediately to prevent it from being copied. Visit the MyIPO (Intellectual Property Corporation of Malaysia) website to learn how to file for copyright to protect your code and creative works, or a patent to protect your unique invention or process.",
    "IF you are considering a significant investment to scale up, THEN first validate the market demand at a larger scale with a pilot program or a limited launch before committing large sums of money.",
    "IF a user has a business idea but is unsure how to structure it, assess its viability, or plan the next steps, THEN the best first step is to complete a Business Model Canvas (BMC). This one-page framework will force you to think through the nine essential building blocks of your business, such as your customer segments, value proposition, and revenue streams. It will give you a clear, professional overview of your idea and instantly highlight any critical gaps you need to address.",
    "IF a user lacks industry experience, needs guidance, or is looking for a mentor to help with their startup, THEN the best way to overcome inexperience is to seek guidance. First, check with your university's entrepreneurship center or faculty for any available mentorship programs. Additionally, use this app's 'Mentor Booking' feature to browse and connect with vetted industry experts who can provide specific advice for your business.",
    "IF you are worried about the legal process of starting up, THEN start by registering a Sole Proprietorship with SSM (Suruhanjaya Syarikat Malaysia) as it is the simplest and most straightforward legal structure for a solo student founder.",
    "IF you are feeling overwhelmed with information, THEN use a suitable dashboard to track your progress and focus on one critical task at a time, such as validating your idea or building your financial plan.",
    "IF the idea is for a regulated industry like food/cosmetics, THEN before launching, you must consult Malaysia's National Pharmaceutical Regulatory Agency (NPRA) for product notification and SIRIM for quality standards to ensure your product is legal and safe for consumers.",
    "IF a user believes that large capital is required to start a business, THEN explain that startups can begin with minimal capital and grow gradually.",
    "IF a user thinks they must form a partnership before launching, THEN advise that solo or small trusted teams are sufficient in early stages.",
    "IF a user wants to create a product before identifying real problems, THEN recommend focusing on community needs first to ensure real added value.",
    "IF a user assumes marketing must be outsourced, THEN inform them that self-managed marketing can be effective and is learnable over time.",
    "IF you feel like you need a co-founder to start, THEN starting solo is perfectly fine, only bring on a co-founder if they have essential skills you lack (e.g., a technical co-founder for a tech idea) because a bad partnership is worse than no partnership.",
    "IF you're thinking of quitting your studies to work on your startup, THEN validate your business as a side project first, use your weekends and free time to test the idea and get your first customers.",
    "IF you're not a marketing expert, THEN focus on organic marketing. Create useful content on one or two social media platforms your customers use, learn basic SEO for your website, and engage directly with your first 100 users.",
    "IF you want to know how a startup application can help you stand out from competitors, THEN use the FAB (Features, Advantages, Benefits) framework to define your unique value.",
    "IF you're trying to get your startup noticed by the government or big organizations, THEN actively seek endorsements or partnerships with credible institutions like your university's entrepreneurship center, MaGIC, or MDEC, building trusts effectively.",
    "IF you want to know how to keep your customers happy once you have them, THEN set up a simple, reliable customer service channel such as a dedicated email or WhatsApp number and respond to all inquiries within 24 hours to build a reputation for great support.",
    "IF you're looking to make some extra money with your app or website, THEN integrate affiliate marketing links from platforms like Shopee, Lazada, or Involve Asia. When a user clicks a link and makes a purchase, you earn a small commission."
]

kb_embeddings = model.encode(knowledge_base, convert_to_tensor=True)

def find_best_rule(question: str):
    question_embedding = model.encode(question, convert_to_tensor=True)
    scores = util.pytorch_cos_sim(question_embedding, kb_embeddings)[0]
    best_idx = scores.argmax().item()
    return knowledge_base[best_idx], float(scores[best_idx])
