// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else {
      throw UnsupportedError(
        'DefaultFirebaseOptions are only supported on the web platform.',
      );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn38pZQZS-TfkD5Kh139lgwkZ_ialHML0',
    appId: '1:544885880175:web:25b8f42c6d30419413e49a',
    messagingSenderId: '544885880175',
    projectId: 'startsmart-650d6',
    authDomain: 'startsmart-650d6.firebaseapp.com',
    storageBucket: 'startsmart-650d6.firebasestorage.app',
    measurementId: 'G-ZL0CFTGNDV',
  );

 
}
